### Numpy

- 벡터 및 행렬 연산에 특화된 라이브러리
- array 단위로 데이터를 관리함

In [1]:
#모듈 import
import numpy as np

In [2]:
#리스트 자료
data1 = [ x for x in range(1,6)]
print(type(data1))
print(data1)

<class 'list'>
[1, 2, 3, 4, 5]


In [3]:
# 리스트를 넘파이 배열로 변환
arr1 = np.array(data1)
print(type(arr1))
print(arr1)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [4]:
dir(arr1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

In [5]:
arr1.shape

(5,)

In [6]:
#2차원 리스트
data2 = [[1,2,3], [4,5,6]]

In [7]:
#2차원 리스트를 넘파이의 2차원 행렬로 변환
arr2 = np.array(data2)
print(arr2)
print(arr2.shape)
#(2,3) 2행 3열의 2차원 행렬

[[1 2 3]
 [4 5 6]]
(2, 3)


In [8]:
# 2차원행렬
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([[7,8,9],[10,11,12]])
print(arr3)
print(arr4)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [9]:
# 같은 자리의 값을 계산함
arr3 + arr4
# print(arr3 - arr4)
# print(arr3 * arr4)
# print(arr3 / arr4)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [10]:
arr3 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [11]:
arr3 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [12]:
#문자열 리스트를 넘파이 배열로 변환
n = ["김철수","홍길동", "손흥민", "이동국", "박지성","홍길동"]
names = np.array([n])
names

array([['김철수', '홍길동', '손흥민', '이동국', '박지성', '홍길동']], dtype='<U3')

In [13]:
#7행 4열의 난수 발생
data = np.random.randn(7,4)
data

array([[-1.9009582 ,  0.2474699 , -1.53290651,  1.7435103 ],
       [-0.82801014, -0.62656327,  0.4743879 ,  0.49855815],
       [-2.73262851, -1.94473002,  1.16601682,  1.05729551],
       [ 0.61809354,  0.42575637,  1.9677672 ,  0.440143  ],
       [ 2.26239289,  0.41903121,  0.97209702, -0.85476434],
       [ 0.41355603, -1.61314537, -0.63430266, -0.79392392],
       [-0.41552526,  0.97516277,  0.47460052,  0.57801077]])

In [14]:
x = np.random.randn(8)
y = np.random.randn(8)

In [15]:
x

array([-0.34493718, -0.32404572, -0.42643304,  0.39505976,  0.28193571,
        0.79530387,  0.03457936,  0.42251144])

In [16]:
y

array([ 0.19863264, -1.2517745 , -1.57378201,  0.28949879, -1.14987929,
       -0.82860706, -0.64092051, -0.30230676])

In [17]:
np.maximum(x,y)

array([ 0.19863264, -0.32404572, -0.42643304,  0.39505976,  0.28193571,
        0.79530387,  0.03457936,  0.42251144])

In [18]:
arr = np.random.randn(5,4)
arr

array([[ 0.65769736, -1.01297526, -0.6184845 ,  0.10996078],
       [-2.28126016, -0.90497717, -0.22575072, -1.31625468],
       [ 0.06511359, -1.77411215,  0.15753005, -0.02604369],
       [-0.54974547,  1.01871141, -0.11970048,  0.7488977 ],
       [-0.75770751,  0.363442  ,  0.65772211,  1.14199671]])

In [19]:
arr.sum()

-4.665940072136971

In [20]:
arr.mean()

-0.23329700360684855

In [21]:
arr.sum(axis=0)

array([-2.86590218, -2.30991116, -0.14868354,  0.65855682])

In [22]:
arr.sum(axis=1)

array([-0.86380162, -4.72824273, -1.5775122 ,  1.09816315,  1.40545331])

In [23]:
#오름차순정렬
np.sort(arr)

array([[-1.01297526, -0.6184845 ,  0.10996078,  0.65769736],
       [-2.28126016, -1.31625468, -0.90497717, -0.22575072],
       [-1.77411215, -0.02604369,  0.06511359,  0.15753005],
       [-0.54974547, -0.11970048,  0.7488977 ,  1.01871141],
       [-0.75770751,  0.363442  ,  0.65772211,  1.14199671]])

In [24]:
#내림차순 정렬 
np.sort(arr, axis=0)[::-1]

array([[ 0.65769736,  1.01871141,  0.65772211,  1.14199671],
       [ 0.06511359,  0.363442  ,  0.15753005,  0.7488977 ],
       [-0.54974547, -0.90497717, -0.11970048,  0.10996078],
       [-0.75770751, -1.01297526, -0.22575072, -0.02604369],
       [-2.28126016, -1.77411215, -0.6184845 , -1.31625468]])

In [25]:
ages = np.array([20, 25, 20, 23, 28, 29, 30, 31,30,40,45])

In [26]:
np.unique(ages)

array([20, 23, 25, 28, 29, 30, 31, 40, 45])

In [27]:
len(np.unique(ages))

9

In [28]:
age_20 = ages[ages > 20]
age_20

array([25, 23, 28, 29, 30, 31, 30, 40, 45])